version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: el-tawla-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "19000:19000"  # Expo
      - "19001:19001"  # Metro bundler
      - "19002:19002"  # Expo DevTools
      - "8081:8081"    # React Native packager
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=host.docker.internal
      - EXPO_PUBLIC_SUPABASE_ANON_KEY=${EXPO_PUBLIC_SUPABASE_ANON_KEY:-your_anon_key}
      - EXPO_PUBLIC_SUPABASE_URL=${EXPO_PUBLIC_SUPABASE_URL:-your_supabase_url}
      - EXPO_ROUTER_APP_ROOT=./app
    command: npx expo start --web --clear
    # network_mode: "host" # Commenté pour permettre l'accès depuis le navigateur local

  # Service de base de données (si nécessaire)
  # db:
  #   image: postgres:14-alpine
  #   container_name: el-tawla-db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=el_tawla
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
